spring.application.name=lms-service
server.servlet.context-path=/lms
server.port=8099
spring.jmx.enabled=false

management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator
management.endpoints.access.default=unrestricted
management.endpoint.prometheus.enabled=true
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.minimum-expected-value.http.server.requests=5ms
management.metrics.distribution.maximum-expected-value.http.server.requests=10s

springdoc.swagger-ui.path=/swagger-ui.html
