apiVersion: v1
kind: ConfigMap
metadata:
  name: event-streaming-service-config
  namespace: ecommerce
data:
  SERVER_PORT: "8101"
  SERVER_SERVLET_CONTEXT_PATH: "/events"
  EVENTS_DEFAULT_PARTITIONS: "3"
  EVENTS_RETENTION_PER_PARTITION: "10000"
  MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
  MANAGEMENT_ENDPOINTS_ACCESS_DEFAULT: "unrestricted"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: "unrestricted"
  MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
