apiVersion: v1
kind: Service
metadata:
  name: event-streaming-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: event-streaming-service
  ports:
    - name: http
      port: 8101
      targetPort: 8101
