apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: payments-service
  ports:
    - name: http
      port: 8100
      targetPort: 8100
